### PR TITLE
fea: added wishlist page

### PR DESCRIPTION
**Pull request by nshanbhag20001412**
image

### CODE REVIEW

**Review by BelideNikhil — APPROVED** [review]
good to go!
maybe have buttons instead of divs and have cursor pointer

**Comment by nshanbhag20001412** [comment]
> good to go! maybe have buttons instead of divs and have cursor pointer

buttons for?

**Comment by nshanbhag20001412** [comment]
> good to go! maybe have buttons instead of divs and have cursor pointer

actually the card from Cl has 2 buttons so there is a div and inside that 2 buttons. I removed 1 button for this card

**Comment by sushmita12345** [comment]
Looks nice! Good to merge.

**Review by sushmita12345 — APPROVED** [review]

**Review by devsurajrai — APPROVED** [review]
Looks good. Keep going.

**Pull request merged**
