### PR TITLE
Cart management

### PR DESCRIPTION
**Pull request by nshanbhag20001412**
image

- https://decorus-ecom.netlify.app/

### CODE REVIEW

**Review by palash23jain — APPROVED** [review]
looks good to me

**Review by siddhigate — APPROVED** [review]
Good to go

**Review by BelideNikhil — APPROVED** [review]
try using fr units instead of percentage in grid, rest looks good!

**Comment by nshanbhag20001412** [comment]
> try using fr units instead of percentage in grid, rest looks good!

noted

**Review by saifudinbadani — APPROVED** [review]
Looks good to merge

**Pull request merged**
