### PR TITLE
fea: Added home page

### PR DESCRIPTION
**Pull request by nshanbhag20001412**
image

- Live Preview :https://npkn6.codesandbox.io/

### CODE REVIEW

**Review by BelideNikhil — APPROVED** [review]
Everything looks good except for the Image size, try using webp or svg format images as these are taking quite some time to load.

**Comment by nshanbhag20001412** [comment]
> Everything looks good except for the Image size, try using webp or svg format images as these are taking quite some time to load.

which image side?

**Comment by nshanbhag20001412** [comment]
> Everything looks good except for the Image size, try using webp or svg format images as these are taking quite some time to load.

> Everything looks good except for the Image size,

which image size?

> try using webp or svg format images as these are taking quite some time to load.

okay noted

**Review by srishti-maurya — APPROVED** [review]
looks good

**Review by AbhishekkGautam — APPROVED** [review]
Good to go 🚀

**Review by manojasarsa — APPROVED** [review]
LGTM 👍

**Pull request merged**
